---
title: "American Option"
author: "Hanyun Zhang"
class: Simulation Application
professor: Chidambaran
---
```{r}
# Random number generator
MYUNIFORM <- function(inputvar)
{
  idum <- inputvar[1]
  numran <- inputvar[2]
  IM1 <- 2147483563
  IM2 <- 2147483399
  IMM1 <- IM1-1
  IA1 <- 40014
  IA2 <- 40692
  IQ1 <- 53668 
  IQ2 <- 52774
  IR1 <- 12211
  IR2 <- 3791
  NTAB <- 32
  NDIV <- as.integer(1+IMM1/NTAB)
  AM=1.0/IM1
  EPS=1.2e-7
  RNMX=1.-EPS
  iv=rep(0,NTAB)
  idum2 <- 123456789
  iy <- 0
  ranx <- rep(0,numran)
  icount <- 1
  for (icount in 1:numran)
  {
    if (idum<=0)
    {
      idum<-max(-idum,1)
      idum2 <- idum
      j<-NTAB+8
      while (j>0)
      {
        k <- as.integer(idum/IQ1)
        idum<-IA1*(idum-k*IQ1)-k*IR1
        if (idum<0){idum <- idum+IM1}
        if(j<= NTAB){iv[j] <- idum}
        j <- j-1
      }
      iy <- iv[1]
    }
    k<-as.integer(idum/IQ1)
    idum<-IA1*(idum-k*IQ1)-k*IR1
    if (idum<0) {idum <- idum+IM1}
    k<-as.integer(idum2/IQ2)
    idum2<-IA2*(idum2-k*IQ2)-k*IR2
    if (idum2<0) {idum2 <- idum2+IM2}
    j<-as.integer(iy/NDIV)+1
    iy<-iv[j]-idum2
    iv[j]<-idum
    if (iy<1) {iy<-iy+IMM1}
    ran2<-min(AM*iy,RNMX)
    ranx[icount]<-ran2
    icount<-icount+1
  }
  
  return(ranx)
}
```

```{r}
# Normal dist generator
MYNORM <- function(ran_c,numran)
{
  a0 <- 2.50662823884
  a1 <- -18.61500062529
  a2 <- 41.39119773534
  a3 <- -25.44106049637

  b0 <- -8.47351093090
  b1 <- 23.08336743743
  b2 <- -21.06224101826
  b3 <- 3.13082909833
  
  c0 <- 0.3374754822726147
  c1 <- 0.9761690190917186
  c2 <- 0.1607979714918209
  c3 <- 0.0276438810333863
  c4 <- 0.0038405729373609
  c5 <- 0.0003951896511919
  c6 <- 0.0000321767881768
  c7 <- 0.0000002888167364
  c8 <- 0.0000003960315187
  
  jcount <- 1
  ran_norm_c <- rep(0,numran)
  while(jcount <= numran)
  {
    u <- ran_c[jcount]
    y <- u-0.5
    if(abs(y)<0.42)
    {
      r <- y*y
      x <- y*(((a3*r+a2)*r+a1)*r+a0)/((((b3*r+b2)*r+b1)*r+b0)*r+1)
    }
    else
    {
      r <- u
      if(y>0){r <- 1-u}
      r <- log(-log(r))
      x <- c0+r*(c1+r*(c2+r*(c3+r*(c4+r*(c5+r*(c6+r*(c7+r*c8)))))))
      if(y<0){x <- -x}
    }
    ran_norm_c[jcount] <- x
    jcount <- jcount+1
  } 
  return(ran_norm_c)
}
```


```{r}
seed=0
numran=100000
inputvar=c(seed,numran)
rand_uniform_c=MYUNIFORM(inputvar)
rand_norm_c=MYNORM(rand_uniform_c,numran)
S0=100
rf=0.03
Strike=100
Volatility=0.25
Maturity=0.5
numpath=1000
numstep=13
Barrier=0
AmericanPut<-function(S0,Strike,rf,Volatility,Maturity,numpath,numstep,Barrier)
{
  St_Vals=matrix(rep(0),nrow=numstep,ncol=numpath)
  Payoff=rep(0,numpath)
  PV_Payoff=rep(0,numpath)
  jcount=1
  lcount=1
  DeltaT=Maturity/numstep
  while (jcount <=numpath)
  {
    St=S0
    for (kcount in 1:numstep)
    {
      St=St*(exp((rf-0.5*(Volatility^2))*DeltaT+Volatility*sqrt(DeltaT)*rand_norm_c[lcount]))
      St_Vals[kcount,jcount]=St
      if(St<=Barrier)
      {
        break
      }
      lcount=lcount+1
      
    }
    Payoff[jcount]=max(Strike-St,0)
    PV_Payoff[jcount]=Payoff[jcount]*exp(-rf*0.5*(kcount-1)/13)
    jcount=jcount+1
  }

  putvalue=mean(PV_Payoff)
  return (putvalue)
}
cat ('American Put Value\n')
put=AmericanPut(S0,Strike,rf,Volatility,Maturity,numpath,numstep,Barrier)
put
cat('Optimal barrier and maximum option value\n')
OptimalBarrier=optimize(AmericanPut,interval=c(0,120),tol=0.00001,maximum=TRUE,S0=100,Strike=100,rf=0.03,Volatility=0.25,Maturity=0.5,numpath=1000,numstep=13)
OptimalBarrier
```

# The American Put value obtained from the binomial spreadsheet equals 5.629005998


