---
title: "CVaR"
author: "Hanyun Zhang"
class: Simulation Application
professor: Chidambaran
---
```{r}
# Random number generator
MYUNIFORM <- function(inputvar)
{
  idum <- inputvar[1]
  numran <- inputvar[2]
  IM1 <- 2147483563
  IM2 <- 2147483399
  IMM1 <- IM1-1
  IA1 <- 40014
  IA2 <- 40692
  IQ1 <- 53668 
  IQ2 <- 52774
  IR1 <- 12211
  IR2 <- 3791
  NTAB <- 32
  NDIV <- as.integer(1+IMM1/NTAB)
  AM=1.0/IM1
  EPS=1.2e-7
  RNMX=1.-EPS
  iv=rep(0,NTAB)
  idum2 <- 123456789
  iy <- 0
  ranx <- rep(0,numran)
  icount <- 1
  for (icount in 1:numran)
  {
    if (idum<=0)
    {
      idum<-max(-idum,1)
      idum2 <- idum
      j<-NTAB+8
      while (j>0)
      {
        k <- as.integer(idum/IQ1)
        idum<-IA1*(idum-k*IQ1)-k*IR1
        if (idum<0){idum <- idum+IM1}
        if(j<= NTAB){iv[j] <- idum}
        j <- j-1
      }
      iy <- iv[1]
    }
    k<-as.integer(idum/IQ1)
    idum<-IA1*(idum-k*IQ1)-k*IR1
    if (idum<0) {idum <- idum+IM1}
    k<-as.integer(idum2/IQ2)
    idum2<-IA2*(idum2-k*IQ2)-k*IR2
    if (idum2<0) {idum2 <- idum2+IM2}
    j<-as.integer(iy/NDIV)+1
    iy<-iv[j]-idum2
    iv[j]<-idum
    if (iy<1) {iy<-iy+IMM1}
    ran2<-min(AM*iy,RNMX)
    ranx[icount]<-ran2
    icount<-icount+1
  }
  
  return(ranx)
}
```

```{r}
# Normal dist generator
MYNORM <- function(ran_c,numran)
{
  a0 <- 2.50662823884
  a1 <- -18.61500062529
  a2 <- 41.39119773534
  a3 <- -25.44106049637

  b0 <- -8.47351093090
  b1 <- 23.08336743743
  b2 <- -21.06224101826
  b3 <- 3.13082909833
  
  c0 <- 0.3374754822726147
  c1 <- 0.9761690190917186
  c2 <- 0.1607979714918209
  c3 <- 0.0276438810333863
  c4 <- 0.0038405729373609
  c5 <- 0.0003951896511919
  c6 <- 0.0000321767881768
  c7 <- 0.0000002888167364
  c8 <- 0.0000003960315187
  
  jcount <- 1
  ran_norm_c <- rep(0,numran)
  while(jcount <= numran)
  {
    u <- ran_c[jcount]
    y <- u-0.5
    if(abs(y)<0.42)
    {
      r <- y*y
      x <- y*(((a3*r+a2)*r+a1)*r+a0)/((((b3*r+b2)*r+b1)*r+b0)*r+1)
    }
    else
    {
      r <- u
      if(y>0){r <- 1-u}
      r <- log(-log(r))
      x <- c0+r*(c1+r*(c2+r*(c3+r*(c4+r*(c5+r*(c6+r*(c7+r*c8)))))))
      if(y<0){x <- -x}
    }
    ran_norm_c[jcount] <- x
    jcount <- jcount+1
  } 
  return(ran_norm_c)
}
```


```{r}
seed=0
numran=1000000
inputvar=c(seed,numran)
rand_uniform_c=MYUNIFORM(inputvar)
rand_norm_c=MYNORM(rand_uniform_c,numran)
numreg=2
DNum=100
portfolio=rep(0,DNum)
portfolio2=rep(0,DNum)
ran100=as.integer(rand_uniform_c*100)+1
for (icount in 1:DNum)
{
  portfolio[icount]=ran100[icount]*10000
}
AMatrix=matrix(rnorm(DNum^2),DNum,DNum)
CovarM=(crossprod(AMatrix))/100
AMatrix=chol(CovarM)
AMatrixt=t(AMatrix)
lcount=1
DeltaT=1/254
Volatility=diag(CovarM)
randZ=rep(0,DNum)
numruns=100
P0=sum(portfolio)
TotalLoss=rep(0,numruns)
PercentLoss=rep(0,numruns)
dollar_rets=rep(0,numruns)
for (icount in 1:numruns)
{
  default=rep(0,DNum)
  loss=rep(0,DNum)
  for (jcount in 1:DNum)
  {
    randZ[jcount]=rand_norm_c[lcount]
    lcount=lcount+1
  }
  ZVals=AMatrixt%*%randZ
  for (jcount in 1:DNum)
  {
    if (-Volatility[jcount]>ZVals[jcount])
    {
      Volatility[jcount]
      ZVals[jcount]
      default[jcount]=1
      loss[jcount]=portfolio[jcount]*0.2
    }
    portfolio2[jcount]=portfolio[jcount]*(exp(((-0.5*Volatility[jcount]^2)*DeltaT)+(sqrt(DeltaT))*ZVals[jcount]))
  }
  P1=sum(portfolio2)
  TotalLoss[icount]=sum(loss)
  #if(icount<15){cat(icount,' ',TotalLoss[icount],"\n")}
  PercentLoss[icount]=TotalLoss[icount]/P0
  dollar_rets[icount]=log(P1/P0)
}
cat ("Total loss for portfolio\n")
quantile(TotalLoss,c(0.05,0.25,0.5,0.75,0.95))
cat ("\nPercentage loss for portoflio \n")
quantile(PercentLoss,c(0.05,0.25,0.5,0.75,0.95))

```

