---
title: "Volatility Smile"
author: Hanyun Zhang
class: Simulation Application
professor: Chidambaran
---

```{r setup, include=FALSE}
MYUNIFORM <- function(inputvar) {
#
# Initialize Constants
#
  IM1<-2147483563
  IM2<-2147483399
  IA1<-40014
  IA2<-40692
  IQ1<-53668
  IQ2<-52774
  IR1<-12211
  IR2<-3791
  NTAB<-32
  EPS<-1.2e-7
  RNMX<-1.-EPS
#
# Transform Variables
#
  IMM1<-IM1-1
  NDIV<-as.integer(1+IMM1/NTAB)
  AM<-1.0/IM1
#
# Initialize variables and arrays
#
  idum<-inputvar[1]
  idum2<-123456789
  numran<-inputvar[2]
  ran2<-0
  iy<-0
  iv<-rep(0,NTAB)
  rand_uniform_c<-rep(0,numran)
#
# Run the random number loop
#  
    icount<-1
  for (icount in 1:numran) {
    if (idum <= 0) {
      idum<-max(-idum,1)
      idum2<-idum
      j<-NTAB+8
      while (j > 0) {
        k=as.integer(idum/IQ1)
        idum<-IA1*(idum-k*IQ1)-k*IR1
        if (idum < 0) {idum=idum+IM1}
        if (j <= NTAB) {iv[j]<-idum}
        j<-j-1
      }
        iy<-iv[1]
      }
    k<-as.integer(idum/IQ1)
    idum<-IA1*(idum-k*IQ1)-k*IR1
    if(idum < 0) {idum=idum+IM1}
    k=as.integer(idum2/IQ2)
    idum2<-IA2*(idum2-k*IQ2)-k*IR2 
    if (idum2 < 0) {idum2<-idum2+IM2}
    j<-as.integer(iy/NDIV)+1
    iy<-iv[j]-idum2
    iv[j]<-idum
    if(iy < 1) {iy<-iy+IMM1}
    ran2<-min(AM*iy,RNMX)
    rand_uniform_c[icount]<-ran2
    }
  return(rand_uniform_c)
}
```

```{r}
#
# Call Uniform Random Number Generator (INPUT: SEED and NUMBER)
#
seed<-0
numran<-1000000
inputvar<-c(seed,numran)
rand_uniform_c<-MYUNIFORM(inputvar)
rand_uniform_c[1:10]
hist(rand_uniform_c)
```

```{r}
#
# Inverse Normal Generator
# Input is vector of uniform random numbers
#
MYNORM <- function(seed,numran) {
  inputvar<-rep(0,2)
  inputvar[1]<-seed
  inputvar[2]<-numran
#
# Call Uniform Random Number Generator
#
  rand_uniform_c<-MYUNIFORM(inputvar)
  # Initialize Constants
  a0<-2.50662823884
  a1<--18.61500062529
  a2<-41.39119773534
  a3<--25.44106049637
  b0<--8.47351093090
  b1<-23.08336743743
  b2<--21.06224101826
  b3<-3.13082909833
  c0<-0.3374754822726147
  c1<-0.9761690190917186
  c2<-0.1607979714918209
  c3<-0.0276438810333863
  c4<-0.0038405729373609
  c5<-0.0003951896511919
  c6<-0.0000321767881768
  c7<-0.0000002888167364
  c8<-0.0000003960315187
#
# Call Uniform Random Number Generator
#
inputvar<-c(seed,numran)
rand_uniform_c<-MYUNIFORM(inputvar)
#
# Loop over set of uniform random numbers and transform
#
  jcount<-1
  rand_norm_c<-rep(0,numran)
  while(jcount <= numran) {
    u<-rand_uniform_c[jcount]
    y<-u-0.5
    if(abs(y) < 0.42) {
      r<-y*y
      x<-y*(((a3*r+a2)*r+a1)*r+a0)/((((b3*r+b2)*r+b1)*r+b0)*r+1)
    } else {
      r<-u
      if(y>0){r<-1-u}
      r<-log(-log(r))
      x<-c0+r*(c1+r*(c2+r*(c3+r*(c4+r*(c5+r*(c6+r*(c7+r*c8)))))))
      if(y<0){x<--x}
    }
#  cat("JCOUNT",jcount,"",u,"",x,"\n")
  rand_norm_c[jcount]<-x
  jcount=jcount+1
  }
  return(rand_norm_c)
}
```

```{r}
#
# Call Normal Random Number Generator (INPUT: UNIFORM RANDOM NUMBER VECTOR)
#
seed<-0
numran<-1000000
rand_norm_c<-MYNORM(seed,numran)
hist(rand_norm_c,xlim=c(-5,5),breaks=20,freq=F)
curve(dnorm(x, mean=0, sd=1),from=-4, to=4,add=TRUE,lwd=2)
rand_norm_c[1:10]
```

```{r}
op_price=function(rf,t,K,S,vol)
{
  count<-1
  numran<-10000
  Option<-rep(0,numran)
  while(count<=numran)
  {
    ST<-S*(exp((rf-0.5*(vol^2))*t+vol*sqrt(t)*rand_norm_c[count]))
    Payoff<- ST-K
    if(Payoff>0) 
    {
      Option[count]<-Payoff
    }
    count <- count +1       
  }
  return(mean(exp(-rf*t)*Option))
}
  
```

```{r}
#date: 2017/12/01
#expiration: 2018/9/21
#Time to Maturity: 294 days
X <- read_excel("options.xlsx")
X
Ks<-X[,4]/1000
prices<-X[,5]
S<-127.88 #spot price
t<-294/365
rf<-0.0239 #risk-free rate
implied_vol<-c()
for(i in 1:nrow(Ks))
{
  K<-Ks[i]
  price1<-prices[i]
  implied_vol[i]<-uniroot(function(x) op_price(rf,t,K,S,x)-price1,c(-2,2))
}
plot(Ks,implied_vol)


